plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    // No more obfuscation on this gamever, so no more `mod` prefix for mod dependencies - no remapping to do!
    implementation("maven.modrinth:lithostitched:${lithostitched_version}-fabric-${lithostitched_mc}")

    // NightConfig
    implementation(include("com.electronwill.night-config:core:${nightconfig_version}"))
    implementation(include("com.electronwill.night-config:toml:${nightconfig_version}"))

    // Mod Menu
    // Note: compileOnly + localRuntime = Only on our instance, not transitive to consumers.
    // All java references to dependencies like this need to be fully optional/guarded against classloading
    compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}")
    localRuntime("com.terraformersmc:modmenu:${project.modmenu_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        configureEach {
            ideConfigGenerated(true)
            property('fabric.log.level', 'debug')
            property('mixin.debug', 'true')
            vmArg('-Xmx6G')
            vmArg('-Xms2G')
        }
        client {
            client()
            setConfigName('Fabric Client')
            runDir('runs/client')
            programArgs('--username', 'Dev')
            // Fabric randomizes devuser name (Player###), we manually specify a fixed one matching Neoforge
        }
        clientExtra {
            client()
            setConfigName('Fabric ClientExtra')
            runDir('runs/client2')
            programArgs('--username', 'Dev2')
            // Fabric randomizes devuser name (Player###), we manually specify a fixed one matching Neoforge
        }
        server {
            server()
            setConfigName('Fabric Server')
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

if (project.findProperty('fabric_modpack_path')) {
    def fabricModpackDest = new File(project.fabric_modpack_path).with { f ->
        f.absolute ? f : new File(System.getProperty('user.home'), project.fabric_modpack_path)
    }
    tasks.register('sendToModpackFab', Copy) {
        group = 'publishing'
        description = "Copies the Fabric dev jar into ${fabricModpackDest}"
        dependsOn tasks.named('jar')
        from tasks.named('jar').flatMap { it.archiveFile }
        into fabricModpackDest
        rename { String fileName ->
            fileName.replace(project.version.toString(), 'dev')
        }
        doLast {
            println "Fabric dev jar sent to: ${fabricModpackDest}"
        }
    }
}
