org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1]
neo_version=21.1.129
neo_version_range=[21.1.129,)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.1
mod_id=natures_spirit
mod_version=2.2.5-1.21.1
mod_group_id=net.hibiscus
terrablender_version=4.1.0.8
