package net.hibiscus.naturespirit.registration;

import net.hibiscus.naturespirit.blocks.PaperLanternBlock;
import net.minecraft.block.*;
import net.minecraft.block.enums.Instrument;
import net.minecraft.block.piston.PistonBehavior;
import net.minecraft.item.ItemGroups;
import net.minecraft.sound.BlockSoundGroup;

import static net.hibiscus.naturespirit.registration.NSRegistryHelper.registerBlock;
import static net.hibiscus.naturespirit.registration.NSRegistryHelper.registerPaperLanternBlock;

public class NSDyeDepotCompatibility {
   public static final Block MAROON_PAPER_LANTERN = registerPaperLanternBlock("maroon_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block ROSE_PAPER_LANTERN = registerPaperLanternBlock("rose_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, MAROON_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block CORAL_PAPER_LANTERN = registerPaperLanternBlock("coral_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block GINGER_PAPER_LANTERN = registerPaperLanternBlock("ginger_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, CORAL_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block TAN_PAPER_LANTERN = registerPaperLanternBlock("tan_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block BEIGE_PAPER_LANTERN = registerPaperLanternBlock("beige_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, TAN_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block AMBER_PAPER_LANTERN = registerPaperLanternBlock("amber_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block OLIVE_PAPER_LANTERN = registerPaperLanternBlock("olive_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, AMBER_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block FOREST_PAPER_LANTERN = registerPaperLanternBlock("forest_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block VERDANT_PAPER_LANTERN = registerPaperLanternBlock("verdant_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block TEAL_PAPER_LANTERN = registerPaperLanternBlock("teal_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, VERDANT_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block MINT_PAPER_LANTERN = registerPaperLanternBlock("mint_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block AQUA_PAPER_LANTERN = registerPaperLanternBlock("aqua_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, MINT_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block SLATE_PAPER_LANTERN = registerPaperLanternBlock("slate_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block NAVY_PAPER_LANTERN = registerPaperLanternBlock("navy_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, SLATE_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);
   public static final Block INDIGO_PAPER_LANTERN = registerPaperLanternBlock("indigo_paper_lantern", new PaperLanternBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).solid().strength(0.5F).sounds(
           BlockSoundGroup.LANTERN).luminance((state) -> 15).nonOpaque().pistonBehavior(PistonBehavior.DESTROY)), NSItemGroups.NS_ITEM_GROUP, NAVY_PAPER_LANTERN, ItemGroups.COLORED_BLOCKS, ItemGroups.FUNCTIONAL);

   public static final Block MAROON_KAOLIN = registerBlock("maroon_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_KAOLIN = registerBlock("rose_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MAROON_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_KAOLIN = registerBlock("coral_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_KAOLIN = registerBlock("ginger_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, CORAL_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_KAOLIN = registerBlock("tan_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_KAOLIN = registerBlock("beige_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, TAN_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_KAOLIN = registerBlock("amber_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_KAOLIN = registerBlock("olive_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, AMBER_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_KAOLIN = registerBlock("forest_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_KAOLIN = registerBlock("verdant_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_KAOLIN = registerBlock("teal_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_KAOLIN = registerBlock("mint_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_KAOLIN = registerBlock("aqua_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MINT_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_KAOLIN = registerBlock("slate_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_KAOLIN = registerBlock("navy_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, SLATE_KAOLIN, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_KAOLIN = registerBlock("indigo_kaolin", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NAVY_KAOLIN, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_KAOLIN_STAIRS = registerBlock("maroon_kaolin_stairs", new StairsBlock(MAROON_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_KAOLIN_STAIRS = registerBlock("rose_kaolin_stairs", new StairsBlock(ROSE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MAROON_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_KAOLIN_STAIRS = registerBlock("coral_kaolin_stairs", new StairsBlock(CORAL_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_KAOLIN_STAIRS = registerBlock("ginger_kaolin_stairs", new StairsBlock(GINGER_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, CORAL_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_KAOLIN_STAIRS = registerBlock("tan_kaolin_stairs", new StairsBlock(TAN_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_KAOLIN_STAIRS = registerBlock("beige_kaolin_stairs", new StairsBlock(BEIGE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, TAN_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_KAOLIN_STAIRS = registerBlock("amber_kaolin_stairs", new StairsBlock(AMBER_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_KAOLIN_STAIRS = registerBlock("olive_kaolin_stairs", new StairsBlock(OLIVE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, AMBER_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_KAOLIN_STAIRS = registerBlock("forest_kaolin_stairs", new StairsBlock(FOREST_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_KAOLIN_STAIRS = registerBlock("verdant_kaolin_stairs", new StairsBlock(VERDANT_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_KAOLIN_STAIRS = registerBlock("teal_kaolin_stairs", new StairsBlock(TEAL_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_KAOLIN_STAIRS = registerBlock("mint_kaolin_stairs", new StairsBlock(MINT_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_KAOLIN_STAIRS = registerBlock("aqua_kaolin_stairs", new StairsBlock(AQUA_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MINT_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_KAOLIN_STAIRS = registerBlock("slate_kaolin_stairs", new StairsBlock(SLATE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_KAOLIN_STAIRS = registerBlock("navy_kaolin_stairs", new StairsBlock(NAVY_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, SLATE_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_KAOLIN_STAIRS = registerBlock("indigo_kaolin_stairs", new StairsBlock(INDIGO_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NAVY_KAOLIN_STAIRS, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_KAOLIN_SLAB = registerBlock("maroon_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_KAOLIN_SLAB = registerBlock("rose_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MAROON_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_KAOLIN_SLAB = registerBlock("coral_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_KAOLIN_SLAB = registerBlock("ginger_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, CORAL_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_KAOLIN_SLAB = registerBlock("tan_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_KAOLIN_SLAB = registerBlock("beige_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, TAN_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_KAOLIN_SLAB = registerBlock("amber_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_KAOLIN_SLAB = registerBlock("olive_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, AMBER_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_KAOLIN_SLAB = registerBlock("forest_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_KAOLIN_SLAB = registerBlock("verdant_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_KAOLIN_SLAB = registerBlock("teal_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_KAOLIN_SLAB = registerBlock("mint_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_KAOLIN_SLAB = registerBlock("aqua_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MINT_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_KAOLIN_SLAB = registerBlock("slate_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_KAOLIN_SLAB = registerBlock("navy_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, SLATE_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_KAOLIN_SLAB = registerBlock("indigo_kaolin_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NAVY_KAOLIN_SLAB, ItemGroups.COLORED_BLOCKS);


   public static final Block MAROON_KAOLIN_BRICKS = registerBlock("maroon_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_KAOLIN_BRICKS = registerBlock("rose_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MAROON_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_KAOLIN_BRICKS = registerBlock("coral_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_KAOLIN_BRICKS = registerBlock("ginger_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, CORAL_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_KAOLIN_BRICKS = registerBlock("tan_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_KAOLIN_BRICKS = registerBlock("beige_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, TAN_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_KAOLIN_BRICKS = registerBlock("amber_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_KAOLIN_BRICKS = registerBlock("olive_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, AMBER_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_KAOLIN_BRICKS = registerBlock("forest_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_KAOLIN_BRICKS = registerBlock("verdant_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_KAOLIN_BRICKS = registerBlock("teal_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_KAOLIN_BRICKS = registerBlock("mint_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_KAOLIN_BRICKS = registerBlock("aqua_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MINT_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_KAOLIN_BRICKS = registerBlock("slate_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_KAOLIN_BRICKS = registerBlock("navy_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, SLATE_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_KAOLIN_BRICKS = registerBlock("indigo_kaolin_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NAVY_KAOLIN_BRICKS, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_KAOLIN_BRICK_STAIRS = registerBlock("maroon_kaolin_brick_stairs", new StairsBlock(MAROON_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_KAOLIN_BRICK_STAIRS = registerBlock("rose_kaolin_brick_stairs", new StairsBlock(ROSE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MAROON_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_KAOLIN_BRICK_STAIRS = registerBlock("coral_kaolin_brick_stairs", new StairsBlock(CORAL_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_KAOLIN_BRICK_STAIRS = registerBlock("ginger_kaolin_brick_stairs", new StairsBlock(GINGER_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, CORAL_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_KAOLIN_BRICK_STAIRS = registerBlock("tan_kaolin_brick_stairs", new StairsBlock(TAN_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_KAOLIN_BRICK_STAIRS = registerBlock("beige_kaolin_brick_stairs", new StairsBlock(BEIGE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, TAN_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_KAOLIN_BRICK_STAIRS = registerBlock("amber_kaolin_brick_stairs", new StairsBlock(AMBER_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_KAOLIN_BRICK_STAIRS = registerBlock("olive_kaolin_brick_stairs", new StairsBlock(OLIVE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, AMBER_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_KAOLIN_BRICK_STAIRS = registerBlock("forest_kaolin_brick_stairs", new StairsBlock(FOREST_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_KAOLIN_BRICK_STAIRS = registerBlock("verdant_kaolin_brick_stairs", new StairsBlock(VERDANT_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_KAOLIN_BRICK_STAIRS = registerBlock("teal_kaolin_brick_stairs", new StairsBlock(TEAL_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_KAOLIN_BRICK_STAIRS = registerBlock("mint_kaolin_brick_stairs", new StairsBlock(MINT_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_KAOLIN_BRICK_STAIRS = registerBlock("aqua_kaolin_brick_stairs", new StairsBlock(AQUA_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MINT_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_KAOLIN_BRICK_STAIRS = registerBlock("slate_kaolin_brick_stairs", new StairsBlock(SLATE_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_KAOLIN_BRICK_STAIRS = registerBlock("navy_kaolin_brick_stairs", new StairsBlock(NAVY_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, SLATE_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_KAOLIN_BRICK_STAIRS = registerBlock("indigo_kaolin_brick_stairs", new StairsBlock(INDIGO_KAOLIN.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NAVY_KAOLIN_BRICK_STAIRS, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_KAOLIN_BRICK_SLAB = registerBlock("maroon_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_KAOLIN_BRICK_SLAB = registerBlock("rose_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MAROON_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_KAOLIN_BRICK_SLAB = registerBlock("coral_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_KAOLIN_BRICK_SLAB = registerBlock("ginger_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, CORAL_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_KAOLIN_BRICK_SLAB = registerBlock("tan_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_KAOLIN_BRICK_SLAB = registerBlock("beige_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, TAN_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_KAOLIN_BRICK_SLAB = registerBlock("amber_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_KAOLIN_BRICK_SLAB = registerBlock("olive_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, AMBER_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_KAOLIN_BRICK_SLAB = registerBlock("forest_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_KAOLIN_BRICK_SLAB = registerBlock("verdant_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_KAOLIN_BRICK_SLAB = registerBlock("teal_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_KAOLIN_BRICK_SLAB = registerBlock("mint_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_KAOLIN_BRICK_SLAB = registerBlock("aqua_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, MINT_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_KAOLIN_BRICK_SLAB = registerBlock("slate_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_KAOLIN_BRICK_SLAB = registerBlock("navy_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, SLATE_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_KAOLIN_BRICK_SLAB = registerBlock("indigo_kaolin_brick_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(1.25F,4.2F)), NSItemGroups.NS_ITEM_GROUP, NAVY_KAOLIN_BRICK_SLAB, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_CHALK = registerBlock("maroon_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_CHALK = registerBlock("rose_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, MAROON_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_CHALK = registerBlock("coral_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_CHALK = registerBlock("ginger_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, CORAL_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_CHALK = registerBlock("tan_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_CHALK = registerBlock("beige_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, TAN_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_CHALK = registerBlock("amber_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_CHALK = registerBlock("olive_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, AMBER_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_CHALK = registerBlock("forest_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_CHALK = registerBlock("verdant_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_CHALK = registerBlock("teal_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_CHALK = registerBlock("mint_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_CHALK = registerBlock("aqua_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, MINT_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_CHALK = registerBlock("slate_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_CHALK = registerBlock("navy_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, SLATE_CHALK, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_CHALK = registerBlock("indigo_chalk", new Block(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NAVY_CHALK, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_CHALK_STAIRS = registerBlock("maroon_chalk_stairs", new StairsBlock(MAROON_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_CHALK_STAIRS = registerBlock("rose_chalk_stairs", new StairsBlock(ROSE_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, MAROON_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_CHALK_STAIRS = registerBlock("coral_chalk_stairs", new StairsBlock(CORAL_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_CHALK_STAIRS = registerBlock("ginger_chalk_stairs", new StairsBlock(GINGER_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, CORAL_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_CHALK_STAIRS = registerBlock("tan_chalk_stairs", new StairsBlock(TAN_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_CHALK_STAIRS = registerBlock("beige_chalk_stairs", new StairsBlock(BEIGE_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, TAN_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_CHALK_STAIRS = registerBlock("amber_chalk_stairs", new StairsBlock(AMBER_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_CHALK_STAIRS = registerBlock("olive_chalk_stairs", new StairsBlock(OLIVE_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, AMBER_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_CHALK_STAIRS = registerBlock("forest_chalk_stairs", new StairsBlock(FOREST_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_CHALK_STAIRS = registerBlock("verdant_chalk_stairs", new StairsBlock(VERDANT_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_CHALK_STAIRS = registerBlock("teal_chalk_stairs", new StairsBlock(TEAL_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_CHALK_STAIRS = registerBlock("mint_chalk_stairs", new StairsBlock(MINT_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_CHALK_STAIRS = registerBlock("aqua_chalk_stairs", new StairsBlock(AQUA_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, MINT_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_CHALK_STAIRS = registerBlock("slate_chalk_stairs", new StairsBlock(SLATE_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_CHALK_STAIRS = registerBlock("navy_chalk_stairs", new StairsBlock(NAVY_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, SLATE_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_CHALK_STAIRS = registerBlock("indigo_chalk_stairs", new StairsBlock(INDIGO_CHALK.getDefaultState(), AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NAVY_CHALK_STAIRS, ItemGroups.COLORED_BLOCKS);

   public static final Block MAROON_CHALK_SLAB = registerBlock("maroon_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DARK_CRIMSON).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BROWN_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block ROSE_CHALK_SLAB = registerBlock("rose_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_MAGENTA).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, MAROON_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block CORAL_CHALK_SLAB = registerBlock("coral_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.RAW_IRON_PINK).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.RED_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block GINGER_CHALK_SLAB = registerBlock("ginger_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_ORANGE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, CORAL_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block TAN_CHALK_SLAB = registerBlock("tan_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.ORANGE_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block BEIGE_CHALK_SLAB = registerBlock("beige_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, TAN_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block AMBER_CHALK_SLAB = registerBlock("amber_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.SPRUCE_BROWN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.YELLOW_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block OLIVE_CHALK_SLAB = registerBlock("olive_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIME).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, AMBER_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block FOREST_CHALK_SLAB = registerBlock("forest_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.EMERALD_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.LIME_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block VERDANT_CHALK_SLAB = registerBlock("verdant_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_GREEN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.GREEN_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block TEAL_CHALK_SLAB = registerBlock("teal_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, VERDANT_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block MINT_CHALK_SLAB = registerBlock("mint_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.CYAN_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block AQUA_CHALK_SLAB = registerBlock("aqua_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.DIAMOND_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, MINT_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block SLATE_CHALK_SLAB = registerBlock("slate_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.WATER_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NSColoredBlocks.BLUE_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block NAVY_CHALK_SLAB = registerBlock("navy_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.CYAN).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, SLATE_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);
   public static final Block INDIGO_CHALK_SLAB = registerBlock("indigo_chalk_slab", new SlabBlock(AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BLUE).instrument(Instrument.BASEDRUM).requiresTool().strength(0.5F)), NSItemGroups.NS_ITEM_GROUP, NAVY_CHALK_SLAB, ItemGroups.COLORED_BLOCKS);

   public static void registerColoredBlocks() {
   }
}
